# contents of pyproject.toml

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "example-package-certifiedp"
version = "0.1.0"
dependencies = [
  "numpy",
  "pandas",
  "scikit-learn",
]

[project.optional-dependencies]
test = ["pytest"]